---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r message=FALSE warning=FALSE}
library(dplyr)
library(readxl)
library(stringr)
library(tidyverse)
library(readr)
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")
options(scipen = 999)

gc()
```

```{r 2}

th2<- read_csv("raw/th2.csv")
th2<- mutate_at(th2, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R2a<- semi_join(th2, users_right, by = "user_id")
R2b<- semi_join(th2, users_right, by = "retweeted_status_user_id")
R2c<- semi_join(th2, users_right, by = "quoted_status_user_id")
R2d<- rbind(R2a, R2b, R2c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R2d, "UEI_tweets/right/RT2.csv")

L2a<- semi_join(th2, users_left, by = "user_id")
L2b<- semi_join(th2, users_left, by = "retweeted_status_user_id")
L2c<- semi_join(th2, users_left, by = "quoted_status_user_id")
L2d<- rbind(L2a, L2b, L2c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L2d, "UEI_tweets/left/LT2.csv")

UEI2<- data.frame(wave = 2,
                 rightT= nrow(R2d),
                 leftT= nrow(L2d),
                 rightE=sum(R2d$engagement),
                 leftE=sum(L2d$engagement),
                 right_UEI=sum(R2d$engagement)/(nrow(R2d)+nrow(L2d)), 
                 left_UEI=sum(L2d$engagement)/(nrow(R2d)+nrow(L2d)))

write.csv(UEI2, file = "UEI_tweets/UEI2.csv")
```

```{r 3 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")
#options(scipen = 999)


th3 <- read_csv("raw/th3.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th3<- mutate_at(th3, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R3a<- semi_join(th3, users_right, by = "user_id")
R3b<- semi_join(th3, users_right, by = "retweeted_status_user_id")
R3c<- semi_join(th3, users_right, by = "quoted_status_user_id")
R3d<- rbind(R3a, R3b, R3c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R3d, "UEI_tweets/right/RT3.csv")

L3a<- semi_join(th3, users_left, by = "user_id")
L3b<- semi_join(th3, users_left, by = "retweeted_status_user_id")
L3c<- semi_join(th3, users_left, by = "quoted_status_user_id")
L3d<- rbind(L3a, L3b, L3c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L3d, "UEI_tweets/left/LT3.csv")

UEI3<- data.frame(wave = 3,
                 rightT= nrow(R3d),
                 leftT= nrow(L3d),
                 rightE=sum(R3d$engagement),
                 leftE=sum(L3d$engagement),
                 right_UEI=sum(R3d$engagement)/(nrow(R3d)+nrow(L3d)), 
                 left_UEI=sum(L3d$engagement)/(nrow(R3d)+nrow(L3d)))

write.csv(UEI3, file = "UEI_tweets/UEI3.csv")
```



```{r 4 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th4<- read_csv("raw/th4.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th4<- mutate_at(th4, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R4a<- semi_join(th4, users_right, by = "user_id")
R4b<- semi_join(th4, users_right, by = "retweeted_status_user_id")
R4c<- semi_join(th4, users_right, by = "quoted_status_user_id")
R4d<- rbind(R4a, R4b, R4c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R4d, "UEI_tweets/right/RT4.csv")

L4a<- semi_join(th4, users_left, by = "user_id")
L4b<- semi_join(th4, users_left, by = "retweeted_status_user_id")
L4c<- semi_join(th4, users_left, by = "quoted_status_user_id")
L4d<- rbind(L4a, L4b, L4c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L4d, "UEI_tweets/left/LT4.csv")

UEI4<- data.frame(wave = 4,
                 rightT= nrow(R4d),
                 leftT= nrow(L4d),
                 rightE=sum(R4d$engagement),
                 leftE=sum(L4d$engagement),
                 right_UEI=sum(R4d$engagement)/(nrow(R4d)+nrow(L4d)), 
                 left_UEI=sum(L4d$engagement)/(nrow(R4d)+nrow(L4d)))

write.csv(UEI4, file = "UEI_tweets/UEI4.csv")
```

```{r 5 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th5<- read_csv("raw/th5.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th5<- mutate_at(th5, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R5a<- semi_join(th5, users_right, by = "user_id")
R5b<- semi_join(th5, users_right, by = "retweeted_status_user_id")
R5c<- semi_join(th5, users_right, by = "quoted_status_user_id")
R5d<- rbind(R5a, R5b, R5c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R5d, "UEI_tweets/right/RT5.csv")

L5a<- semi_join(th5, users_left, by = "user_id")
L5b<- semi_join(th5, users_left, by = "retweeted_status_user_id")
L5c<- semi_join(th5, users_left, by = "quoted_status_user_id")
L5d<- rbind(L5a, L5b, L5c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L5d, "UEI_tweets/left/LT5.csv")

UEI5<- data.frame(wave = 5,
                 rightT= nrow(R5d),
                 leftT= nrow(L5d),
                 rightE=sum(R5d$engagement),
                 leftE=sum(L5d$engagement),
                 right_UEI=sum(R5d$engagement)/(nrow(R5d)+nrow(L5d)), 
                 left_UEI=sum(L5d$engagement)/(nrow(R5d)+nrow(L5d)))

write.csv(UEI5, file = "UEI_tweets/UEI5.csv")
```




```{r 6 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th6<- read_csv("raw/th6.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th6<- mutate_at(th6, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R6a<- semi_join(th6, users_right, by = "user_id")
R6b<- semi_join(th6, users_right, by = "retweeted_status_user_id")
R6c<- semi_join(th6, users_right, by = "quoted_status_user_id")
R6d<- rbind(R6a, R6b, R6c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R6d, "UEI_tweets/right/RT6.csv")

L6a<- semi_join(th6, users_left, by = "user_id")
L6b<- semi_join(th6, users_left, by = "retweeted_status_user_id")
L6c<- semi_join(th6, users_left, by = "quoted_status_user_id")
L6d<- rbind(L6a, L6b, L6c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L6d, "UEI_tweets/left/LT6.csv")

UEI6<- data.frame(wave = 6,
                 rightT= nrow(R6d),
                 leftT= nrow(L6d),
                 rightE=sum(R6d$engagement),
                 leftE=sum(L6d$engagement),
                 right_UEI=sum(R6d$engagement)/(nrow(R6d)+nrow(L6d)), 
                 left_UEI=sum(L6d$engagement)/(nrow(R6d)+nrow(L6d)))

write.csv(UEI6, file = "UEI_tweets/UEI6.csv")

```

```{r 7 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th7<- read_csv("raw/th7.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th7<- mutate_at(th7, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R7a<- semi_join(th7, users_right, by = "user_id")
R7b<- semi_join(th7, users_right, by = "retweeted_status_user_id")
R7c<- semi_join(th7, users_right, by = "quoted_status_user_id")
R7d<- rbind(R7a, R7b, R7c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R7d, "UEI_tweets/right/RT7.csv")

L7a<- semi_join(th7, users_left, by = "user_id")
L7b<- semi_join(th7, users_left, by = "retweeted_status_user_id")
L7c<- semi_join(th7, users_left, by = "quoted_status_user_id")
L7d<- rbind(L7a, L7b, L7c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L7d, "UEI_tweets/left/LT7.csv")

UEI7<- data.frame(wave = 7,
                 rightT= nrow(R7d),
                 leftT= nrow(L7d),
                 rightE=sum(R7d$engagement),
                 leftE=sum(L7d$engagement),
                 right_UEI=sum(R7d$engagement)/(nrow(R7d)+nrow(L7d)), 
                 left_UEI=sum(L7d$engagement)/(nrow(R7d)+nrow(L7d)))

write.csv(UEI7, file = "UEI_tweets/UEI7.csv")
```

```{r 8 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th8<- read_csv("raw/th8.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th8<- mutate_at(th8, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R8a<- semi_join(th8, users_right, by = "user_id")
R8b<- semi_join(th8, users_right, by = "retweeted_status_user_id")
R8c<- semi_join(th8, users_right, by = "quoted_status_user_id")
R8d<- rbind(R8a, R8b, R8c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R8d, "UEI_tweets/right/RT8.csv")

L8a<- semi_join(th8, users_left, by = "user_id")
L8b<- semi_join(th8, users_left, by = "retweeted_status_user_id")
L8c<- semi_join(th8, users_left, by = "quoted_status_user_id")
L8d<- rbind(L8a, L8b, L8c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L8d, "UEI_tweets/left/LT8.csv")

UEI8<- data.frame(wave = 8,
                 rightT= nrow(R8d),
                 leftT= nrow(L8d),
                 rightE=sum(R8d$engagement),
                 leftE=sum(L8d$engagement),
                 right_UEI=sum(R8d$engagement)/(nrow(R8d)+nrow(L8d)), 
                 left_UEI=sum(L8d$engagement)/(nrow(R8d)+nrow(L8d)))

write.csv(UEI8, file = "UEI_tweets/UEI8.csv")

```

```{r 9 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th9<- read_csv("raw/th9.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th9<- mutate_at(th9, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R9a<- semi_join(th9, users_right, by = "user_id")
R9b<- semi_join(th9, users_right, by = "retweeted_status_user_id")
R9c<- semi_join(th9, users_right, by = "quoted_status_user_id")
R9d<- rbind(R9a, R9b, R9c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R9d, "UEI_tweets/right/RT9.csv")

L9a<- semi_join(th9, users_left, by = "user_id")
L9b<- semi_join(th9, users_left, by = "retweeted_status_user_id")
L9c<- semi_join(th9, users_left, by = "quoted_status_user_id")
L9d<- rbind(L9a, L9b, L9c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L9d, "UEI_tweets/left/LT9.csv")

UEI9<- data.frame(wave = 9,
                 rightT= nrow(R9d),
                 leftT= nrow(L9d),
                 rightE=sum(R9d$engagement),
                 leftE=sum(L9d$engagement),
                 right_UEI=sum(R9d$engagement)/(nrow(R9d)+nrow(L9d)), 
                 left_UEI=sum(L9d$engagement)/(nrow(R9d)+nrow(L9d)))

write.csv(UEI9, file = "UEI_tweets/UEI9.csv")
```

```{r 10 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th10<- read_csv("raw/th10.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th10<- mutate_at(th10, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R10a<- semi_join(th10, users_right, by = "user_id")
R10b<- semi_join(th10, users_right, by = "retweeted_status_user_id")
R10c<- semi_join(th10, users_right, by = "quoted_status_user_id")
R10d<- rbind(R10a, R10b, R10c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R10d, "UEI_tweets/right/RT10.csv")

L10a<- semi_join(th10, users_left, by = "user_id")
L10b<- semi_join(th10, users_left, by = "retweeted_status_user_id")
L10c<- semi_join(th10, users_left, by = "quoted_status_user_id")
L10d<- rbind(L10a, L10b, L10c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L10d, "UEI_tweets/left/LT10.csv")

UEI10<- data.frame(wave = 10,
                 rightT= nrow(R10d),
                 leftT= nrow(L10d),
                 rightE=sum(R10d$engagement),
                 leftE=sum(L10d$engagement),
                 right_UEI=sum(R10d$engagement)/(nrow(R10d)+nrow(L10d)), 
                 left_UEI=sum(L10d$engagement)/(nrow(R10d)+nrow(L10d)))

write.csv(UEI10, file = "UEI_tweets/UEI10.csv")

```

```{r 11 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th11<- read_csv("raw/th11.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th11<- mutate_at(th11, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R11a<- semi_join(th11, users_right, by = "user_id")
R11b<- semi_join(th11, users_right, by = "retweeted_status_user_id")
R11c<- semi_join(th11, users_right, by = "quoted_status_user_id")
R11d<- rbind(R11a, R11b, R11c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R11d, "UEI_tweets/right/RT11.csv")

L11a<- semi_join(th11, users_left, by = "user_id")
L11b<- semi_join(th11, users_left, by = "retweeted_status_user_id")
L11c<- semi_join(th11, users_left, by = "quoted_status_user_id")
L11d<- rbind(L11a, L11b, L11c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L11d, "UEI_tweets/left/LT11.csv")

UEI11<- data.frame(wave = 11,
                 rightT= nrow(R11d),
                 leftT= nrow(L11d),
                 rightE=sum(R11d$engagement),
                 leftE=sum(L11d$engagement),
                 right_UEI=sum(R11d$engagement)/(nrow(R11d)+nrow(L11d)), 
                 left_UEI=sum(L11d$engagement)/(nrow(R11d)+nrow(L11d)))

write.csv(UEI11, file = "UEI_tweets/UEI11.csv")
```

```{r 12 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th12<- read_csv("raw/th12.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th12<- mutate_at(th12, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R12a<- semi_join(th12, users_right, by = "user_id")
R12b<- semi_join(th12, users_right, by = "retweeted_status_user_id")
R12c<- semi_join(th12, users_right, by = "quoted_status_user_id")
R12d<- rbind(R12a, R12b, R12c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R12d, "UEI_tweets/right/RT12.csv")

L12a<- semi_join(th12, users_left, by = "user_id")
L12b<- semi_join(th12, users_left, by = "retweeted_status_user_id")
L12c<- semi_join(th12, users_left, by = "quoted_status_user_id")
L12d<- rbind(L12a, L12b, L12c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L12d, "UEI_tweets/left/LT12.csv")

UEI12<- data.frame(wave = 12,
                 rightT= nrow(R12d),
                 leftT= nrow(L12d),
                 rightE=sum(R12d$engagement),
                 leftE=sum(L12d$engagement),
                 right_UEI=sum(R12d$engagement)/(nrow(R12d)+nrow(L12d)), 
                 left_UEI=sum(L12d$engagement)/(nrow(R12d)+nrow(L12d)))

write.csv(UEI12, file = "UEI_tweets/UEI12.csv")


```

```{r 13 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th13<- read_csv("raw/th13.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th13<- mutate_at(th13, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R13a<- semi_join(th13, users_right, by = "user_id")
R13b<- semi_join(th13, users_right, by = "retweeted_status_user_id")
R13c<- semi_join(th13, users_right, by = "quoted_status_user_id")
R13d<- rbind(R13a, R13b, R13c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R13d, "UEI_tweets/right/RT13.csv")

L13a<- semi_join(th13, users_left, by = "user_id")
L13b<- semi_join(th13, users_left, by = "retweeted_status_user_id")
L13c<- semi_join(th13, users_left, by = "quoted_status_user_id")
L13d<- rbind(L13a, L13b, L13c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L13d, "UEI_tweets/left/LT13.csv")

UEI13<- data.frame(wave = 13,
                 rightT= nrow(R13d),
                 leftT= nrow(L13d),
                 rightE=sum(R13d$engagement),
                 leftE=sum(L13d$engagement),
                 right_UEI=sum(R13d$engagement)/(nrow(R13d)+nrow(L13d)),
                 left_UEI=sum(L13d$engagement)/(nrow(R13d)+nrow(L13d)))

write.csv(UEI13, file = "UEI_tweets/UEI13.csv")
```

```{r 14 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th14<- read_csv("raw/th14.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th14<- mutate_at(th14, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R14a<- semi_join(th14, users_right, by = "user_id")
R14b<- semi_join(th14, users_right, by = "retweeted_status_user_id")
R14c<- semi_join(th14, users_right, by = "quoted_status_user_id")
R14d<- rbind(R14a, R14b, R14c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R14d, "UEI_tweets/right/RT14.csv")

L14a<- semi_join(th14, users_left, by = "user_id")
L14b<- semi_join(th14, users_left, by = "retweeted_status_user_id")
L14c<- semi_join(th14, users_left, by = "quoted_status_user_id")
L14d<- rbind(L14a, L14b, L14c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L14d, "UEI_tweets/left/LT14.csv")

UEI14<- data.frame(wave = 14,
                 rightT= nrow(R14d),
                 leftT= nrow(L14d),
                 rightE=sum(R14d$engagement),
                 leftE=sum(L14d$engagement),
                 right_UEI=sum(R14d$engagement)/(nrow(R14d)+nrow(L14d)),
                 left_UEI=sum(L14d$engagement)/(nrow(R14d)+nrow(L14d)))

write.csv(UEI14, file = "UEI_tweets/UEI14.csv")

```

```{r 15 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")


th15<- read_csv("raw/th15.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th15<- mutate_at(th15, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R15a<- semi_join(th15, users_right, by = "user_id")
R15b<- semi_join(th15, users_right, by = "retweeted_status_user_id")
R15c<- semi_join(th15, users_right, by = "quoted_status_user_id")
R15d<- rbind(R15a, R15b, R15c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R15d, "UEI_tweets/right/RT15.csv")

L15a<- semi_join(th15, users_left, by = "user_id")
L15b<- semi_join(th15, users_left, by = "retweeted_status_user_id")
L15c<- semi_join(th15, users_left, by = "quoted_status_user_id")
L15d<- rbind(L15a, L15b, L15c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L15d, "UEI_tweets/left/LT15.csv")

UEI15<- data.frame(wave = 15,
                 rightT= nrow(R15d),
                 leftT= nrow(L15d),
                 rightE=sum(R15d$engagement),
                 leftE=sum(L15d$engagement),
                 right_UEI=sum(R15d$engagement)/(nrow(R15d)+nrow(L15d)),
                 left_UEI=sum(L15d$engagement)/(nrow(R15d)+nrow(L15d)))

write.csv(UEI15, file = "UEI_tweets/UEI15.csv")

```

```{r 16 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th16<- read_csv("raw/th16.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th16<- mutate_at(th16, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R16a<- semi_join(th16, users_right, by = "user_id")
R16b<- semi_join(th16, users_right, by = "retweeted_status_user_id")
R16c<- semi_join(th16, users_right, by = "quoted_status_user_id")
R16d<- rbind(R16a, R16b, R16c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R16d, "UEI_tweets/right/RT16.csv")

L16a<- semi_join(th16, users_left, by = "user_id")
L16b<- semi_join(th16, users_left, by = "retweeted_status_user_id")
L16c<- semi_join(th16, users_left, by = "quoted_status_user_id")
L16d<- rbind(L16a, L16b, L16c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L16d, "UEI_tweets/left/LT16.csv")

UEI16<- data.frame(wave = 16,
                 rightT= nrow(R16d),
                 leftT= nrow(L16d),
                 rightE=sum(R16d$engagement),
                 leftE=sum(L16d$engagement),
                 right_UEI=sum(R16d$engagement)/(nrow(R16d)+nrow(L16d)),
                 left_UEI=sum(L16d$engagement)/(nrow(R16d)+nrow(L16d)))

write.csv(UEI16, file = "UEI_tweets/UEI16.csv")
```

```{r 17 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th17<- read_csv("raw/th17.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th17<- mutate_at(th17, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R17a<- semi_join(th17, users_right, by = "user_id")
R17b<- semi_join(th17, users_right, by = "retweeted_status_user_id")
R17c<- semi_join(th17, users_right, by = "quoted_status_user_id")
R17d<- rbind(R17a, R17b, R17c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R17d, "UEI_tweets/right/RT17.csv")

L17a<- semi_join(th17, users_left, by = "user_id")
L17b<- semi_join(th17, users_left, by = "retweeted_status_user_id")
L17c<- semi_join(th17, users_left, by = "quoted_status_user_id")
L17d<- rbind(L17a, L17b, L17c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L17d, "UEI_tweets/left/LT17.csv")

UEI17<- data.frame(wave = 17,
                 rightT= nrow(R17d),
                 leftT= nrow(L17d),
                 rightE=sum(R17d$engagement),
                 leftE=sum(L17d$engagement),
                 right_UEI=sum(R17d$engagement)/(nrow(R17d)+nrow(L17d)),
                 left_UEI=sum(L17d$engagement)/(nrow(R17d)+nrow(L17d)))

write.csv(UEI17, file = "UEI_tweets/UEI17.csv")

```

```{r 18 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th18<- read_csv("raw/th18.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th18<- mutate_at(th18, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R18a<- semi_join(th18, users_right, by = "user_id")
R18b<- semi_join(th18, users_right, by = "retweeted_status_user_id")
R18c<- semi_join(th18, users_right, by = "quoted_status_user_id")
R18d<- rbind(R18a, R18b, R18c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R18d, "UEI_tweets/right/RT18.csv")

L18a<- semi_join(th18, users_left, by = "user_id")
L18b<- semi_join(th18, users_left, by = "retweeted_status_user_id")
L18c<- semi_join(th18, users_left, by = "quoted_status_user_id")
L18d<- rbind(L18a, L18b, L18c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L18d, "UEI_tweets/left/LT18.csv")

UEI18<- data.frame(wave = 18,
                 rightT= nrow(R18d),
                 leftT= nrow(L18d),
                 rightE=sum(R18d$engagement),
                 leftE=sum(L18d$engagement),
                 right_UEI=sum(R18d$engagement)/(nrow(R18d)+nrow(L18d)),
                 left_UEI=sum(L18d$engagement)/(nrow(R18d)+nrow(L18d)))

write.csv(UEI18, file = "UEI_tweets/UEI18.csv")

```

```{r 19 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th19<- read_csv("raw/th19.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th19<- mutate_at(th19, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R19a<- semi_join(th19, users_right, by = "user_id")
R19b<- semi_join(th19, users_right, by = "retweeted_status_user_id")
R19c<- semi_join(th19, users_right, by = "quoted_status_user_id")
R19d<- rbind(R19a, R19b, R19c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R19d, "UEI_tweets/right/RT19.csv")

L19a<- semi_join(th19, users_left, by = "user_id")
L19b<- semi_join(th19, users_left, by = "retweeted_status_user_id")
L19c<- semi_join(th19, users_left, by = "quoted_status_user_id")
L19d<- rbind(L19a, L19b, L19c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L19d, "UEI_tweets/left/LT19.csv")

UEI19<- data.frame(wave = 19,
                 rightT= nrow(R19d),
                 leftT= nrow(L19d),
                 rightE=sum(R19d$engagement),
                 leftE=sum(L19d$engagement),
                 right_UEI=sum(R19d$engagement)/(nrow(R19d)+nrow(L19d)),
                 left_UEI=sum(L19d$engagement)/(nrow(R19d)+nrow(L19d)))

write.csv(UEI19, file = "UEI_tweets/UEI19.csv")

```

```{r 20 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th20<- read_csv("raw/th20.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th20<- mutate_at(th20, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R20a<- semi_join(th20, users_right, by = "user_id")
R20b<- semi_join(th20, users_right, by = "retweeted_status_user_id")
R20c<- semi_join(th20, users_right, by = "quoted_status_user_id")
R20d<- rbind(R20a, R20b, R20c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R20d, "UEI_tweets/right/RT20.csv")

L20a<- semi_join(th20, users_left, by = "user_id")
L20b<- semi_join(th20, users_left, by = "retweeted_status_user_id")
L20c<- semi_join(th20, users_left, by = "quoted_status_user_id")
L20d<- rbind(L20a, L20b, L20c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L20d, "UEI_tweets/left/LT20.csv")

UEI20<- data.frame(wave = 20,
                 rightT= nrow(R20d),
                 leftT= nrow(L20d),
                 rightE=sum(R20d$engagement),
                 leftE=sum(L20d$engagement),
                 right_UEI=sum(R20d$engagement)/(nrow(R20d)+nrow(L20d)),
                 left_UEI=sum(L20d$engagement)/(nrow(R20d)+nrow(L20d)))

write.csv(UEI20, file = "UEI_tweets/UEI20.csv")

```

```{r 21 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th21<- read_csv("raw/th21.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th21<- mutate_at(th21, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R21a<- semi_join(th21, users_right, by = "user_id")
R21b<- semi_join(th21, users_right, by = "retweeted_status_user_id")
R21c<- semi_join(th21, users_right, by = "quoted_status_user_id")
R21d<- rbind(R21a, R21b, R21c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R21d, "UEI_tweets/right/RT21.csv")

L21a<- semi_join(th21, users_left, by = "user_id")
L21b<- semi_join(th21, users_left, by = "retweeted_status_user_id")
L21c<- semi_join(th21, users_left, by = "quoted_status_user_id")
L21d<- rbind(L21a, L21b, L21c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L21d, "UEI_tweets/left/LT21.csv")

UEI21<- data.frame(wave = 21,
                 rightT= nrow(R21d),
                 leftT= nrow(L21d),
                 rightE=sum(R21d$engagement),
                 leftE=sum(L21d$engagement),
                 right_UEI=sum(R21d$engagement)/(nrow(R21d)+nrow(L21d)),
                 left_UEI=sum(L21d$engagement)/(nrow(R21d)+nrow(L21d)))

write.csv(UEI21, file = "UEI_tweets/UEI21.csv")

```

```{r 22 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th22<- read_csv("raw/th22.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th22<- mutate_at(th22, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R22a<- semi_join(th22, users_right, by = "user_id")
R22b<- semi_join(th22, users_right, by = "retweeted_status_user_id")
R22c<- semi_join(th22, users_right, by = "quoted_status_user_id")
R22d<- rbind(R22a, R22b, R22c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R22d, "UEI_tweets/right/RT22.csv")

L22a<- semi_join(th22, users_left, by = "user_id")
L22b<- semi_join(th22, users_left, by = "retweeted_status_user_id")
L22c<- semi_join(th22, users_left, by = "quoted_status_user_id")
L22d<- rbind(L22a, L22b, L22c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L22d, "UEI_tweets/left/LT22.csv")

UEI22<- data.frame(wave = 22,
                 rightT= nrow(R22d),
                 leftT= nrow(L22d),
                 rightE=sum(R22d$engagement),
                 leftE=sum(L22d$engagement),
                 right_UEI=sum(R22d$engagement)/(nrow(R22d)+nrow(L22d)),
                 left_UEI=sum(L22d$engagement)/(nrow(R22d)+nrow(L22d)))

write.csv(UEI22, file = "UEI_tweets/UEI22.csv")

```

```{r 23 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th23<- read_csv("raw/th23.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th23<- mutate_at(th23, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R23a<- semi_join(th23, users_right, by = "user_id")
R23b<- semi_join(th23, users_right, by = "retweeted_status_user_id")
R23c<- semi_join(th23, users_right, by = "quoted_status_user_id")
R23d<- rbind(R23a, R23b, R23c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R23d, "UEI_tweets/right/RT23.csv")

L23a<- semi_join(th23, users_left, by = "user_id")
L23b<- semi_join(th23, users_left, by = "retweeted_status_user_id")
L23c<- semi_join(th23, users_left, by = "quoted_status_user_id")
L23d<- rbind(L23a, L23b, L23c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L23d, "UEI_tweets/left/LT23.csv")

UEI23<- data.frame(wave = 23,
                 rightT= nrow(R23d),
                 leftT= nrow(L23d),
                 rightE=sum(R23d$engagement),
                 leftE=sum(L23d$engagement),
                 right_UEI=sum(R23d$engagement)/(nrow(R23d)+nrow(L23d)),
                 left_UEI=sum(L23d$engagement)/(nrow(R23d)+nrow(L23d)))

write.csv(UEI23, file = "UEI_tweets/UEI23.csv")

```

```{r 24 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th24<- read_csv("raw/th24.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th24<- mutate_at(th24, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R24a<- semi_join(th24, users_right, by = "user_id")
R24b<- semi_join(th24, users_right, by = "retweeted_status_user_id")
R24c<- semi_join(th24, users_right, by = "quoted_status_user_id")
R24d<- rbind(R24a, R24b, R24c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R24d, "UEI_tweets/right/RT24.csv")

L24a<- semi_join(th24, users_left, by = "user_id")
L24b<- semi_join(th24, users_left, by = "retweeted_status_user_id")
L24c<- semi_join(th24, users_left, by = "quoted_status_user_id")
L24d<- rbind(L24a, L24b, L24c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L24d, "UEI_tweets/left/LT24.csv")

UEI24<- data.frame(wave = 24,
                 rightT= nrow(R24d),
                 leftT= nrow(L24d),
                 rightE=sum(R24d$engagement),
                 leftE=sum(L24d$engagement),
                 right_UEI=sum(R24d$engagement)/(nrow(R24d)+nrow(L24d)),
                 left_UEI=sum(L24d$engagement)/(nrow(R24d)+nrow(L24d)))

write.csv(UEI24, file = "UEI_tweets/UEI24.csv")

```

```{r 25 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th25<- read_csv("raw/th25.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th25<- mutate_at(th25, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R25a<- semi_join(th25, users_right, by = "user_id")
R25b<- semi_join(th25, users_right, by = "retweeted_status_user_id")
R25c<- semi_join(th25, users_right, by = "quoted_status_user_id")
R25d<- rbind(R25a, R25b, R25c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R25d, "UEI_tweets/right/RT25.csv")

L25a<- semi_join(th25, users_left, by = "user_id")
L25b<- semi_join(th25, users_left, by = "retweeted_status_user_id")
L25c<- semi_join(th25, users_left, by = "quoted_status_user_id")
L25d<- rbind(L25a, L25b, L25c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L25d, "UEI_tweets/left/LT25.csv")

UEI25<- data.frame(wave = 25,
                 rightT= nrow(R25d),
                 leftT= nrow(L25d),
                 rightE=sum(R25d$engagement),
                 leftE=sum(L25d$engagement),
                 right_UEI=sum(R25d$engagement)/(nrow(R25d)+nrow(L25d)),
                 left_UEI=sum(L25d$engagement)/(nrow(R25d)+nrow(L25d)))

write.csv(UEI25, file = "UEI_tweets/UEI25.csv")

```

```{r 26 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th26<- read_csv("raw/th26.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th26<- mutate_at(th26, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R26a<- semi_join(th26, users_right, by = "user_id")
R26b<- semi_join(th26, users_right, by = "retweeted_status_user_id")
R26c<- semi_join(th26, users_right, by = "quoted_status_user_id")
R26d<- rbind(R26a, R26b, R26c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R26d, "UEI_tweets/right/RT26.csv")

L26a<- semi_join(th26, users_left, by = "user_id")
L26b<- semi_join(th26, users_left, by = "retweeted_status_user_id")
L26c<- semi_join(th26, users_left, by = "quoted_status_user_id")
L26d<- rbind(L26a, L26b, L26c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L26d, "UEI_tweets/left/LT26.csv")

UEI26<- data.frame(wave = 26,
                 rightT= nrow(R26d),
                 leftT= nrow(L26d),
                 rightE=sum(R26d$engagement),
                 leftE=sum(L26d$engagement),
                 right_UEI=sum(R26d$engagement)/(nrow(R26d)+nrow(L26d)),
                 left_UEI=sum(L26d$engagement)/(nrow(R26d)+nrow(L26d)))

write.csv(UEI26, file = "UEI_tweets/UEI26.csv")

```

```{r 27 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th27<- read_csv("raw/th27.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th27<- mutate_at(th27, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R27a<- semi_join(th27, users_right, by = "user_id")
R27b<- semi_join(th27, users_right, by = "retweeted_status_user_id")
R27c<- semi_join(th27, users_right, by = "quoted_status_user_id")
R27d<- rbind(R27a, R27b, R27c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R27d, "UEI_tweets/right/RT27.csv")

L27a<- semi_join(th27, users_left, by = "user_id")
L27b<- semi_join(th27, users_left, by = "retweeted_status_user_id")
L27c<- semi_join(th27, users_left, by = "quoted_status_user_id")
L27d<- rbind(L27a, L27b, L27c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L27d, "UEI_tweets/left/LT27.csv")

UEI27<- data.frame(wave = 27,
                 rightT= nrow(R27d),
                 leftT= nrow(L27d),
                 rightE=sum(R27d$engagement),
                 leftE=sum(L27d$engagement),
                 right_UEI=sum(R27d$engagement)/(nrow(R27d)+nrow(L27d)),
                 left_UEI=sum(L27d$engagement)/(nrow(R27d)+nrow(L27d)))

write.csv(UEI27, file = "UEI_tweets/UEI27.csv")

```

```{r 28 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th28<- read_csv("raw/th28.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th28<- mutate_at(th28, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R28a<- semi_join(th28, users_right, by = "user_id")
R28b<- semi_join(th28, users_right, by = "retweeted_status_user_id")
R28c<- semi_join(th28, users_right, by = "quoted_status_user_id")
R28d<- rbind(R28a, R28b, R28c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R28d, "UEI_tweets/right/RT28.csv")

L28a<- semi_join(th28, users_left, by = "user_id")
L28b<- semi_join(th28, users_left, by = "retweeted_status_user_id")
L28c<- semi_join(th28, users_left, by = "quoted_status_user_id")
L28d<- rbind(L28a, L28b, L28c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L28d, "UEI_tweets/left/LT28.csv")

UEI28<- data.frame(wave = 28,
                 rightT= nrow(R28d),
                 leftT= nrow(L28d),
                 rightE=sum(R28d$engagement),
                 leftE=sum(L28d$engagement),
                 right_UEI=sum(R28d$engagement)/(nrow(R28d)+nrow(L28d)),
                 left_UEI=sum(L28d$engagement)/(nrow(R28d)+nrow(L28d)))

write.csv(UEI28, file = "UEI_tweets/UEI28.csv")

```

```{r 29 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th29<- read_csv("raw/th29.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th29<- mutate_at(th29, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R29a<- semi_join(th29, users_right, by = "user_id")
R29b<- semi_join(th29, users_right, by = "retweeted_status_user_id")
R29c<- semi_join(th29, users_right, by = "quoted_status_user_id")
R29d<- rbind(R29a, R29b, R29c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R29d, "UEI_tweets/right/RT29.csv")

L29a<- semi_join(th29, users_left, by = "user_id")
L29b<- semi_join(th29, users_left, by = "retweeted_status_user_id")
L29c<- semi_join(th29, users_left, by = "quoted_status_user_id")
L29d<- rbind(L29a, L29b, L29c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L29d, "UEI_tweets/left/LT29.csv")

UEI29<- data.frame(wave = 29,
                 rightT= nrow(R29d),
                 leftT= nrow(L29d),
                 rightE=sum(R29d$engagement),
                 leftE=sum(L29d$engagement),
                 right_UEI=sum(R29d$engagement)/(nrow(R29d)+nrow(L29d)),
                 left_UEI=sum(L29d$engagement)/(nrow(R29d)+nrow(L29d)))

write.csv(UEI29, file = "UEI_tweets/UEI29.csv")

```

```{r 30 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th30<- read_csv("raw/th30.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th30<- mutate_at(th30, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R30a<- semi_join(th30, users_right, by = "user_id")
R30b<- semi_join(th30, users_right, by = "retweeted_status_user_id")
R30c<- semi_join(th30, users_right, by = "quoted_status_user_id")
R30d<- rbind(R30a, R30b, R30c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R30d, "UEI_tweets/right/RT30.csv")

L30a<- semi_join(th30, users_left, by = "user_id")
L30b<- semi_join(th30, users_left, by = "retweeted_status_user_id")
L30c<- semi_join(th30, users_left, by = "quoted_status_user_id")
L30d<- rbind(L30a, L30b, L30c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L30d, "UEI_tweets/left/LT30.csv")

UEI30<- data.frame(wave = 30,
                 rightT= nrow(R30d),
                 leftT= nrow(L30d),
                 rightE=sum(R30d$engagement),
                 leftE=sum(L30d$engagement),
                 right_UEI=sum(R30d$engagement)/(nrow(R30d)+nrow(L30d)),
                 left_UEI=sum(L30d$engagement)/(nrow(R30d)+nrow(L30d)))

write.csv(UEI30, file = "UEI_tweets/UEI30.csv")

```

```{r 31 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th31<- read_csv("raw/th31.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th31<- mutate_at(th31, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R31a<- semi_join(th31, users_right, by = "user_id")
R31b<- semi_join(th31, users_right, by = "retweeted_status_user_id")
R31c<- semi_join(th31, users_right, by = "quoted_status_user_id")
R31d<- rbind(R31a, R31b, R31c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R31d, "UEI_tweets/right/RT31.csv")

L31a<- semi_join(th31, users_left, by = "user_id")
L31b<- semi_join(th31, users_left, by = "retweeted_status_user_id")
L31c<- semi_join(th31, users_left, by = "quoted_status_user_id")
L31d<- rbind(L31a, L31b, L31c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L31d, "UEI_tweets/left/LT31.csv")

UEI31<- data.frame(wave = 31,
                 rightT= nrow(R31d),
                 leftT= nrow(L31d),
                 rightE=sum(R31d$engagement),
                 leftE=sum(L31d$engagement),
                 right_UEI=sum(R31d$engagement)/(nrow(R31d)+nrow(L31d)),
                 left_UEI=sum(L31d$engagement)/(nrow(R31d)+nrow(L31d)))

write.csv(UEI31, file = "UEI_tweets/UEI31.csv")

```

```{r 32 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th32<- read_csv("raw/th32.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th32<- mutate_at(th32, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R32a<- semi_join(th32, users_right, by = "user_id")
R32b<- semi_join(th32, users_right, by = "retweeted_status_user_id")
R32c<- semi_join(th32, users_right, by = "quoted_status_user_id")
R32d<- rbind(R32a, R32b, R32c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R32d, "UEI_tweets/right/RT32.csv")

L32a<- semi_join(th32, users_left, by = "user_id")
L32b<- semi_join(th32, users_left, by = "retweeted_status_user_id")
L32c<- semi_join(th32, users_left, by = "quoted_status_user_id")
L32d<- rbind(L32a, L32b, L32c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L32d, "UEI_tweets/left/LT32.csv")

UEI32<- data.frame(wave = 32,
                 rightT= nrow(R32d),
                 leftT= nrow(L32d),
                 rightE=sum(R32d$engagement),
                 leftE=sum(L32d$engagement),
                 right_UEI=sum(R32d$engagement)/(nrow(R32d)+nrow(L32d)),
                 left_UEI=sum(L32d$engagement)/(nrow(R32d)+nrow(L32d)))

write.csv(UEI32, file = "UEI_tweets/UEI32.csv")

```

```{r 33 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th33<- read_csv("raw/th33.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th33<- mutate_at(th33, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R33a<- semi_join(th33, users_right, by = "user_id")
R33b<- semi_join(th33, users_right, by = "retweeted_status_user_id")
R33c<- semi_join(th33, users_right, by = "quoted_status_user_id")
R33d<- rbind(R33a, R33b, R33c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R33d, "UEI_tweets/right/RT33.csv")

L33a<- semi_join(th33, users_left, by = "user_id")
L33b<- semi_join(th33, users_left, by = "retweeted_status_user_id")
L33c<- semi_join(th33, users_left, by = "quoted_status_user_id")
L33d<- rbind(L33a, L33b, L33c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L33d, "UEI_tweets/left/LT33.csv")

UEI33<- data.frame(wave = 33,
                 rightT= nrow(R33d),
                 leftT= nrow(L33d),
                 rightE=sum(R33d$engagement),
                 leftE=sum(L33d$engagement),
                 right_UEI=sum(R33d$engagement)/(nrow(R33d)+nrow(L33d)),
                 left_UEI=sum(L33d$engagement)/(nrow(R33d)+nrow(L33d)))

write.csv(UEI33, file = "UEI_tweets/UEI33.csv")

```

```{r 34 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th34<- read_csv("raw/th34.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th34<- mutate_at(th34, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R34a<- semi_join(th34, users_right, by = "user_id")
R34b<- semi_join(th34, users_right, by = "retweeted_status_user_id")
R34c<- semi_join(th34, users_right, by = "quoted_status_user_id")
R34d<- rbind(R34a, R34b, R34c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R34d, "UEI_tweets/right/RT34.csv")

L34a<- semi_join(th34, users_left, by = "user_id")
L34b<- semi_join(th34, users_left, by = "retweeted_status_user_id")
L34c<- semi_join(th34, users_left, by = "quoted_status_user_id")
L34d<- rbind(L34a, L34b, L34c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L34d, "UEI_tweets/left/LT34.csv")

UEI34<- data.frame(wave = 34,
                 rightT= nrow(R34d),
                 leftT= nrow(L34d),
                 rightE=sum(R34d$engagement),
                 leftE=sum(L34d$engagement),
                 right_UEI=sum(R34d$engagement)/(nrow(R34d)+nrow(L34d)),
                 left_UEI=sum(L34d$engagement)/(nrow(R34d)+nrow(L34d)))

write.csv(UEI34, file = "UEI_tweets/UEI34.csv")

```

```{r 35 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th35<- read_csv("raw/th35.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th35<- mutate_at(th35, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R35a<- semi_join(th35, users_right, by = "user_id")
R35b<- semi_join(th35, users_right, by = "retweeted_status_user_id")
R35c<- semi_join(th35, users_right, by = "quoted_status_user_id")
R35d<- rbind(R35a, R35b, R35c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R35d, "UEI_tweets/right/RT35.csv")

L35a<- semi_join(th35, users_left, by = "user_id")
L35b<- semi_join(th35, users_left, by = "retweeted_status_user_id")
L35c<- semi_join(th35, users_left, by = "quoted_status_user_id")
L35d<- rbind(L35a, L35b, L35c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L35d, "UEI_tweets/left/LT35.csv")

UEI35<- data.frame(wave = 35,
                 rightT= nrow(R35d),
                 leftT= nrow(L35d),
                 rightE=sum(R35d$engagement),
                 leftE=sum(L35d$engagement),
                 right_UEI=sum(R35d$engagement)/(nrow(R35d)+nrow(L35d)),
                 left_UEI=sum(L35d$engagement)/(nrow(R35d)+nrow(L35d)))

write.csv(UEI35, file = "UEI_tweets/UEI35.csv")

```

```{r 36 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th36<- read_csv("raw/th36.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th36<- mutate_at(th36, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R36a<- semi_join(th36, users_right, by = "user_id")
R36b<- semi_join(th36, users_right, by = "retweeted_status_user_id")
R36c<- semi_join(th36, users_right, by = "quoted_status_user_id")
R36d<- rbind(R36a, R36b, R36c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R36d, "UEI_tweets/right/RT36.csv")

L36a<- semi_join(th36, users_left, by = "user_id")
L36b<- semi_join(th36, users_left, by = "retweeted_status_user_id")
L36c<- semi_join(th36, users_left, by = "quoted_status_user_id")
L36d<- rbind(L36a, L36b, L36c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L36d, "UEI_tweets/left/LT36.csv")

UEI36<- data.frame(wave = 36,
                 rightT= nrow(R36d),
                 leftT= nrow(L36d),
                 rightE=sum(R36d$engagement),
                 leftE=sum(L36d$engagement),
                 right_UEI=sum(R36d$engagement)/(nrow(R36d)+nrow(L36d)),
                 left_UEI=sum(L36d$engagement)/(nrow(R36d)+nrow(L36d)))

write.csv(UEI36, file = "UEI_tweets/UEI36.csv")

```

```{r 37 message = FALSE warning = FALSE}
rm(list = ls())
gc()
users_left<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-left", col_names = TRUE, col_types = "numeric")
users_right<-read_excel("C:/Users/Administrator/Desktop/Wagner_Vaccine_Influencers (2).xlsx", sheet = "US-right", col_names = TRUE, col_types = "numeric")



th37<- read_csv("raw/th37.csv", col_types = cols(user_id = col_number(), 
    retweeted_status_user_id = col_number(), 
    quoted_status_user_id = col_number()))
th37<- mutate_at(th37, c("user_followers_count", "retweeted_status_user_followers_count", "retweeted_status_retweet_count", "retweeted_status_favorite_count", "retweeted_status_reply_count","quoted_status_user_followers_count", "quoted_status_retweet_count", "quoted_status_favorite_count", "quoted_status_reply_count" ), ~replace(., is.na(.), 0))

R37a<- semi_join(th37, users_right, by = "user_id")
R37b<- semi_join(th37, users_right, by = "retweeted_status_user_id")
R37c<- semi_join(th37, users_right, by = "quoted_status_user_id")
R37d<- rbind(R37a, R37b, R37c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(R37d, "UEI_tweets/right/RT37.csv")

L37a<- semi_join(th37, users_left, by = "user_id")
L37b<- semi_join(th37, users_left, by = "retweeted_status_user_id")
L37c<- semi_join(th37, users_left, by = "quoted_status_user_id")
L37d<- rbind(L37a, L37b, L37c)%>% group_by(id)%>% filter (! duplicated(id))%>% mutate(engagement= user_followers_count + retweeted_status_user_followers_count + retweeted_status_retweet_count + retweeted_status_favorite_count + retweeted_status_reply_count + quoted_status_user_followers_count + quoted_status_retweet_count + quoted_status_favorite_count + quoted_status_reply_count)
write.csv(L37d, "UEI_tweets/left/LT37.csv")

UEI37<- data.frame(wave = 37,
                 rightT= nrow(R37d),
                 leftT= nrow(L37d),
                 rightE=sum(R37d$engagement),
                 leftE=sum(L37d$engagement),
                 right_UEI=sum(R37d$engagement)/(nrow(R37d)+nrow(L37d)),
                 left_UEI=sum(L37d$engagement)/(nrow(R37d)+nrow(L37d)))

write.csv(UEI37, file = "UEI_tweets/UEI37.csv")

```

```{r}
files = list.files(pattern="UEI_tweets/Twitter_Index/*.csv")
tbl <- list.files(path = "UEI_tweets/Twitter_Index/",
               pattern = "*.csv", 
               full.names = T) %>%  map_df(~read_csv(., col_types = cols(wave = col_number(), rightT = col_number(), leftT= col_number(), rightE= col_number(), leftE = col_number(), right_UEI = col_number(), left_UEI = col_number()))) 

UEI<- tbl[c(2:8)]
write.csv(UEI, file = "UEI_tweets/UEI.csv")
```

